# Generated by Django 3.2 on 2021-04-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_registro', models.IntegerField(unique=True)),
                ('datos', models.JSONField()),
                ('fecha', models.DateTimeField()),
                ('procesado', models.BooleanField(default=False)),
                ('hash', models.CharField(blank=True, max_length=32, null=True)),
                ('salt', models.CharField(blank=True, max_length=40, null=True)),
                ('comprobante', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
