# Generated by Django 3.2 on 2021-04-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alastria', '0002_alter_registro_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='hash',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
