# Generated by Django 3.2 on 2021-04-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alastria', '0005_alter_registro_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='archivos',
            field=models.TextField(default='archivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registro',
            name='datos',
            field=models.TextField(),
        ),
    ]
