# Generated by Django 3.2 on 2021-04-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alastria', '0006_auto_20210421_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='archivos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='salt',
            field=models.CharField(default='hash', max_length=40),
            preserve_default=False,
        ),
    ]
