# Generated by Django 5.0.4 on 2024-04-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alastria", "0007_auto_20210421_2023"),
    ]

    operations = [
        migrations.AddField(
            model_name="registro",
            name="callback_url",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
