# Generated by Django 5.0.4 on 2024-04-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alastria", "0008_registro_callback_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="registro",
            name="estado",
            field=models.CharField(default="pendiente", max_length=20),
        ),
    ]
