# Generated by Django 5.0.4 on 2024-05-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alastria", "0011_alter_registro_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registro",
            name="comprobante",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
